[profile.default]
src = "src"
out = "out"
libs = ["lib"]
test = "test"
script = "script"
solc_version = "0.8.24"
evm_version = "cancun"
optimizer = true
optimizer_runs = 200
via_ir = true
ffi = true            # handy for tooling; disable if your CI forbids
fs_permissions = [{ access = "read", path = "./" }]

[fmt]
line_length = 100
tab_width = 4
bracket_spacing = false
int_types = "short"
quote_style = "double"
func_attrs_with_params_multiline = "all"

[rpc_endpoints]
base_sepolia = "${RPC_URL}"

[etherscan]
# If you want sourcify/etherscan verification later:
base_sepolia = { key = "${ETHERSCAN_API_KEY}" }
